{% set name = "docquery" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docquery-{{ version }}.tar.gz
  sha256: f422e6fe1548355dfccac5a665631b2119388620b0ac102940cf1f3f992d5fee

build:
  entry_points:
    - docquery = docquery.cmd.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pytorch >=1.0
    - pdf2image
    - pdfplumber
    - pillow
    - pydantic
    - pytesseract
    - requests
    - transformers >=4.21

test:
  imports:
    - docquery
  commands:
    - pip check
    - docquery --help
  requires:
    - pip

about:
  home: https://github.com/impira/docquery
  summary: An easy way to extract information from documents.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
